### ISSUE TITLE
Update aan nieuwe implementatie

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/universal-judge#28]
- [x] Met #20 moet nagekeken worden of de beschrijving van de evaluatie van de testcases nog in orde is.
- [x] Beschrijf toestand na #26.
- [x] Het ziet er naar uit dat de implementatie van #24 net iets anders gaat zijn dan wat de tekst beschrijft, pas de tekst lichtjes aan.
