### ISSUE TITLE
Tracker for deprecated stuff

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/universal-judge#418]
This issue can track deprecated stuff we still support, which we can remove if there are no more known users.

- [ ] deprecated field `runs` in the test suites
- [ ] `plan.json` as default for test suite names in the config
- [ ] deprecated names `testplan` and `plan_name` in the config (for `test_suite`)
- [ ] deprecated field `evaluators` (for `functions`)
- [ ] deprecated fields `evaluator` (for `oracle`)
- [ ] ignored field `essential`
- [ ] ignored field `show_expected`
- [ ] statements can have return values in the DSL
